### ISSUE TITLE
Is there any way to config BFP for swimlane source?

### ISSUE THREAD

**Issue by molyom** [XRM-OSS/D365-PowerKanban#11]

**Comment by DigitalFlow** [comment]
Hi there,

not yet. But it is on the todo list.

Kind Regards,
Florian

**Comment by tylerboswell** [comment]
I do this by creating an Option set that mirrors the BPF stages and then a workflow that will populate the option set based on the BPF stage.

**Comment by DigitalFlow** [comment]
That's what we usually do as well.

But if you want "the full experience" of BPFs, we would also have to show a dialog after moving of the record which asks for field inputs of the BPF steps.

**Comment by tylerboswell** [comment]
I handled this by added steps to my reverse workflow (update BPF stage on Option set update) to stop the process if one of the required fields is missing. Could be better, but it tells the user to make sure those fields are filled out.

**Comment by DigitalFlow** [comment]
Closing this for #91, where it will be implemented and design choices can be discussed.
