### ISSUE TITLE
Question: How we can validate data after change the state?

### ISSUE THREAD

**Issue by molyom** [XRM-OSS/D365-PowerKanban#15]
If we need to validate some filed value and if they are not correct, it back to the last step. (May just possible with JS? form configuration we cannot define it? )

**Comment by DigitalFlow** [comment]
Hi @molyom,

You can achieve this with custom script callbacks.
Here you can find an example for a custom script that can check and prevent stage transitions: 
https://github.com/DigitalFlow/D365-PowerKanban/blob/master/src/web/data/exampleExternalScript.js

You can embed it as described here:
https://github.com/DigitalFlow/D365-PowerKanban#config-with-custom-code-callback-on-primary-record-drag-and-drop

You can just fetch your data using the supplied webapiclient instance (or Xrm.WebApi) and return a promise.
If your promise contains an object like `{ preventDefault: true }`, stages will not be changed and you can show a custom alert (using window.alert or Xrm.Utility.alertDialog).

If you just need simple status transition checks, configure your statuscode field to use status transitions, they will be taken care of automatically.

Kind Regards,
Florian

**Comment by molyom** [comment]
Thanks for your reply. 
But I mean something like this: 
{
    "primaryEntity": {

        "Isvalidate": true,  // here you can call your function that if return true the state change can be happened. 

Example: 
 "Isvalidate": boardViewExtender.checkRecordRegardingChangeState (if return true. state will change if not, ... .)

        "allowTransitions": true,
        "logicalName": "incident",
        "swimLaneSource": "statuscode",
        "notificationLookup": "oss_incidentid",
        "subscriptionLookup": "oss_incidentid",
        "transitionCallback": "boardViewExtender.onStateTransition"
    },
    "secondaryEntity": {
        "allowTransitions": true,
        "logicalName": "task",
        "notificationLookup": "oss_taskid",
        "parentLookup": "regardingobjectid",
        "subscriptionLookup": "oss_taskid",
        "swimLaneSource": "statuscode"
    }
}

**Comment by DigitalFlow** [comment]
You can already do this with the transitionCallback as described above, I don't really see the use of having a second callback that does not add any extra functionality.

**Comment by DigitalFlow** [comment]
Hi @molyom,

As per the above comment, I'll close this issue.
Please reopen if you feel the need to further discuss.

Kind Regards,
Florian
