### ISSUE TITLE
The Board selector is not limited to current entity. 

### ISSUE THREAD

**Issue by molyom** [XRM-OSS/D365-PowerKanban#25]
In Opportunity grid view, if i chose other board, (ex. Case) below opportunity title of Dynamics 365, it shows me the Case records. 
I mean, it was better, if the view of the board be limited to current entity. Now it show you form Kanban Config, all of your configurations.

**Comment by DigitalFlow** [comment]
Hi @molyom,

can you check your configurations?
Inside the PowerKanban Config entity, there is a field named 'Entity Logical Name', which defines for which entity this config is to be used for.
This will be filtered on, so in your example all configs would be shown in the selector, which have the same name in this field as the current entity.

At my side this works, can you verify at your side?

Kind Regards,
Florian

**Comment by molyom** [comment]
My configuration was badly configured. I correct it and it is working well, now.
