### ISSUE TITLE
What type and naming convention does the config need to be?

### ISSUE THREAD

**Issue by dustin5515** [XRM-OSS/D365-PowerKanban#27]
Is the config supposed to be of type script with a certain extension?

**Comment by DigitalFlow** [comment]
Hi there,

Configs are no longer webresources, but records of the powerkanban entity.
Pleased Check out the Wiki for a quick introduction: https://github.com/XRM-OSS/D365-PowerKanban/wiki/Configuration

If any questions remain, please ask or close the issue otherwise.

Kind Regards,
Florian
