### ISSUE TITLE
Subscription Lookup

### ISSUE THREAD

**Issue by MaxMonkman** [XRM-OSS/D365-PowerKanban#28]
Hi, 

sorry if this is the wrong place to go for support. 

I'm looking to enable the Subscription / Notification features, however I'm not sure what the sub / notif lookups in the Config file is meant to be point to? Do I need to create a Subscription and Notification Entity and have a lookup to those on my Kanban Card entity?

Thanks

**Comment by DigitalFlow** [comment]
Hi @MaxMonkman,

no need for creating a new entity, subscription and notification entities are already shipped within the solution.
There is a wiki entry for setting up the subscription / notification feature, I hope this helps you:

https://github.com/XRM-OSS/D365-PowerKanban/wiki/Subscriptions-and-Notifications

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Closing this issue, please reopen if the wiki link did not answer your question.
