### ISSUE TITLE
Displaying custom forms

### ISSUE THREAD

**Issue by alex188888** [XRM-OSS/D365-PowerKanban#30]
Hello @DigitalFlow 

Assuming I would like to pop up a custom dialog box as presented here:
https://github.com/XRM-OSS/D365-PowerKanban/wiki/Custom-code-on-move-of-item,-Displaying-custom-forms

Where do I need to insert the code provided in the example? 

Many thanks for your help

**Comment by DigitalFlow** [comment]
Hi @alex188888,

you can create a custom web resource inside D365 for achieving this.
An example of how a script like that might look like can be found here: https://github.com/XRM-OSS/D365-PowerKanban/blob/master/src/web/data/exampleExternalScript.js

You can then load it in your powerkanban config as described here: https://github.com/XRM-OSS/D365-PowerKanban/wiki/Custom-code-on-move-of-item,-Displaying-custom-forms

Please update if you need more help or close if you succeeded 👍 

Kind Regards,
Florian

**Comment by alex188888** [comment]
Hello @DigitalFlow,

Thank you very much for your replay another question is translation can we translate it two other languages ?

**Comment by DigitalFlow** [comment]
Hi @alex188888,

translations are possible, you can handle them completely in your custom script.

Example:
```JS
const dialogOptions = {
    "1033": {
        title: "Resolve case",
        fields: {
            "subject": {
                label: "Subject",
                type: "text",
                required: true,
                subtext: "Please enter a summary how the case was solved"
            }
        }
    },
    "1031": {
        title: "Case Abschließen",
        fields: {
            "subject": {
                label: "Betreff",
                type: "text",
                required: true,
                subtext: "Bitte schreiben Sie eine Zusammenfassung, wie die Anfrage geschlossen wurde"
            }
        }
    }
};

const uiLcid = Xrm.Page.context.getUserLcid().toString();
context.showForm(dialogOptions[uiLcid] || dialogOptions["1033"]);
```

**Comment by DigitalFlow** [comment]
Hi @alex188888,

did my response help you?
I'll close this issue for now, please reopen if you need further assistance.
