### ISSUE TITLE
Add filtering options

### ISSUE THREAD

**Issue by DigitalFlow** [XRM-OSS/D365-PowerKanban#33]
For some cases, the search in all fields does not suffice.
Therefore a filter should be implemented which allows to define filter criteria per field.

**Comment by tylerboswell** [comment]
Hello. Is there any update on this, or perhaps a way for us to implement one?

**Comment by DigitalFlow** [comment]
Hi @tylerboswell,

no progress yet, but I should be able to continue here soon.

Kind regards,
Florian

**Comment by DigitalFlow** [comment]
Closing this for #90, where it is currently being developed and will be part of the next release.
Design decisions can be discussed there.
