### ISSUE TITLE
Issue clickin on lookups

### ISSUE THREAD

**Issue by pab74** [XRM-OSS/D365-PowerKanban#34]
Hello, I have just noticed that clicking on a Lookup generates an invalid open url and therefore the user receives an error
https://XXX.crm4.dynamics.com/main.aspx?appid=XX1068-f59b-XX-8d69-8XXdd1aa9f7&forceUCI=1&newWindow=true&pagetype=entityrecord&etn=HERE MISSING the custom entity name
Could you help me please?

**Comment by DigitalFlow** [comment]
Hey @pab74,

Can you please give me the version of D365-PowerKanban that you are using?
If you are below v0.9.15, please update to this version.
What you describe is a bug which was fixed quite a long time ago in #8 (which you reported at that time).

Kind Regards,
Florian

**Comment by pab74** [comment]
Hello,
thank you for the reply. Currently I have the latest release, v0.9.15
[image: image.png]
I will try to reinstall and see what happens.

Il giorno lun 26 ott 2020 alle ore 11:51 Florian Krönert <
notifications@github.com> ha scritto:

**Comment by pab74** [comment]
here it is the link to the video
https://www.loom.com/share/1c6adf78fb454bea8998e0f7a61b86aa?from_recorder=1

**Comment by DigitalFlow** [comment]
This was closed automatically due to the PR being merged. I'll publish an updated solution very soon, probably tomorrow.

**Comment by DigitalFlow** [comment]
Hi  @pab74,

I just released v0.9.16 which fixes your issue, please test.
If the issues persist, please reopen this issue.

Kind Regards,
Florian
