### ISSUE TITLE
Importing Error Into a Power App Model Driven APP

### ISSUE THREAD

**Issue by onelove2283** [XRM-OSS/D365-PowerKanban#39]
There are missing dependencies. Install the following solutions before installing this one: "msdynce_Service (9.0.5.56)"

**Comment by DigitalFlow** [comment]
Any chance this is a bare organization without any preinstalled modules?
The solution currently contains an example configuration for case and task, thus import in bare organizations fails.

Excluding the references to a separate solution is on the to do list, afterwards this error will not occur anymore.

**Comment by onelove2283** [comment]
You are correct, I don't have cases in my environment.

Sent from my Sprint Samsung Galaxy A71 5G.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DigitalFlow** [comment]
Expect a solution without these dependencies tomorrow

**Comment by DigitalFlow** [comment]
Hi @onelove2283,

Can you download v0.9.18 and try if this version works for you?

Kind Regards,
Florian

**Comment by onelove2283** [comment]
Will do!

Sent from my Sprint Samsung Galaxy A71 5G.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DigitalFlow** [comment]
I'll close this issue as import should work without issues.
If any issues occur, please reopen.
