### ISSUE TITLE
Views are not filtered based on modern app used

### ISSUE THREAD

**Issue by ArsenAghajanyan** [XRM-OSS/D365-PowerKanban#40]
In Dynamics, we can filter which views we want to add to a particular UCI APP.
PowerKanban does not take this into consideration and brings all the views no matter within which APP it is used. 🙂

**Comment by DigitalFlow** [comment]
Hi @ArsenAghajanyan,

you're right, this is not done yet.
Right now you can use the `hiddenViews` and `visibleViews` properties in the PowerKanban Config for limiting the views which are selectable as shown [here](https://github.com/XRM-OSS/D365-PowerKanban/wiki/Configuration#json-scheme)

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @ArsenAghajanyan,

since release v0.9.22 we use the default view selector for the primary entity. This makes PowerKanban take the view filter definition of the model driven app into consideration.

Please have a try :)

Kind Regards,
Florian
