### ISSUE TITLE
Does not show de new custom cards and nes custom views

### ISSUE THREAD

**Issue by theofilomoraes** [XRM-OSS/D365-PowerKanban#42]
Hi, 
I am using the Power Kanban with a custom entity.
I have created a new Card and a new View, but that don´t reflect in kanban

Look my json config

{
    "primaryEntity": {
        "logicalName": "cr880_demandas",
        "swimLaneSource": "statuscode",
        "defaultView": "Demandas deste ano"
    },
    "secondaryEntity": {
        "logicalName": "task",
        "parentLookup": "regardingobjectid",
        "swimLaneSource": "statuscode"
    }
}

**Comment by DigitalFlow** [comment]
HI @theofilomoraes,

did this issue solve itself?

Kind Regards,
Florian
