### ISSUE TITLE
Error Cannot read property 'AttributeType' of undefinied when user Optionset

### ISSUE THREAD

**Issue by theofilomoraes** [XRM-OSS/D365-PowerKanban#43]
Hi, 
I have the error message "Error Cannot read property 'AttributeType' of undefinied"
I am using optionset in swimLaneSource 

This is a basic kanban, look the JSON:

{
    "primaryEntity": {
        "logicalName": "cr880_demandas",
        "swimLaneSource": "cr880_situacaokanban"
    }
}

**Comment by DigitalFlow** [comment]
Hey @theofilomoraes,

there are two explanations that I can think of:
- Your attribute is not named "cr880_situacaokanban", can you double check whether your entity "cr880_demandas" really contains a field that is named that way?
- In the latest release, metadata is cached in the sessionStorage. So if you created the field after the metadata was loaded once, you have to restart your browser. The metadata calls are quite costly, so this is why they are cached in the latest  versions, the performance boost is insane.

Kind Regards,
Florian

**Comment by theofilomoraes** [comment]
Hi @DigitalFlow 

Maybe the  problem was the metadata cached. Now is working
Thank you

Best regards
