### ISSUE TITLE
Lookup in custom forms when I move item

### ISSUE THREAD

**Issue by theofilomoraes** [XRM-OSS/D365-PowerKanban#44]
Hi @DigitalFlow 

I am trying put a lookup in a custom form to fill some data when I move item
But the lookup doesn´t working, it shows only a text input.

Script attached
[boadViewExtenderWithContactLookcup.txt](https://github.com/XRM-OSS/D365-PowerKanban/files/5703080/boadViewExtenderWithContactLookcup.txt)

Tks!

Best regards

Theo

**Comment by DigitalFlow** [comment]
Hi @theofilomoraes,

in your code you wrote `fetchxml:` where it should be `fetchXml:`.
Can you change that and try again?

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @theofilomoraes,

any news on this?
I'd close this issue otherwise.

Kind Regards,
Florian
