### ISSUE TITLE
u is not a function

### ISSUE THREAD

**Issue by pab74** [XRM-OSS/D365-PowerKanban#46]
Hi Florian,
happy new year. I have updated Powerkanban (v 0.9.20) in sandbox and production env. In production it is working fine, but in sandbox I have this strange behaviour. When I try to drag and drop a task to another lane I receive "u is not a function" error and the item is not moved to the new lane... any idea? Thanks and sorry for bothering you.
Paolo
https://www.loom.com/share/ee8b75a3297440dda0e15f0536e062a0

**Comment by DigitalFlow** [comment]
Hi @pab74,

I wish you a happy new year too 👍
You’re not bothering at all, this issue tracker can also be used for helping out on issues such as yours.
Can you check your config in your sandbox org and maybe submit it in here if you fail to find the issue?

I suspect that you registered a transitionCallback which is invalid.

Kind Regards,
Florian

**Comment by pab74** [comment]
as usual you are right! :-)
the culprit was transitionCallback. I deleted it and now it works fine
Super thank you
Cheers
Paolo

Il giorno sab 2 gen 2021 alle ore 00:32 Florian Krönert <
notifications@github.com> ha scritto:

**Comment by DigitalFlow** [comment]
Glad that it’s resolved, I’ll close this issue 😊
Have a nice day.
