### ISSUE TITLE
Subscribe error

### ISSUE THREAD

**Issue by BugsOli** [XRM-OSS/D365-PowerKanban#47]
Hello Florian and Happy New Year!

Still using your awesome component and I just wanted to try out the Notification & Subscription feature.
I have setup a step on Post Create of an email with this config:
{
    "parentLookupName": "regardingobjectid",
    "subscriptionLookupName": "oss_incidentid",
    "notificationLookupName": "oss_incidentid",
    "notifyCurrentUser": true,
    "xtlCondition": "IsEqual(Value('directioncode'), false)",
    "messageConfig": {
        "default": "A new email regarding this case has been received"
    },
	"globalNotificationConfig": {
		"default": "New emails regarding cases have been created, click to open"
	}
}

However, when I click on the subscribe bell in the Kanban, the process fails with this error in the console:

`An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property 'oss_incidentid' which only has property annotations in the payload but no property value was found in the payload`

Can you advise on what I'm doing wrong please?

Thanks in advance

**Comment by BugsOli** [comment]
Never mind ;-)
I've found out why I'm having a problem in my UAT environment, the lookups have not been deployed properly!

**Comment by DigitalFlow** [comment]
Hi @BugsOli,

thanks for posting your issue, I'm glad that you like this project :)
Sorry for being late, but as you found out, the subcriptionLookupName and notificationLookupName have to be the names of existing fields on the subscription / notification entity, that point to the entity where the feature should be used.

You can create your own fields as well and pass the names of these.

Kind Regards,
Florian
