### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by alexy18** [XRM-OSS/D365-PowerKanban#48]
Hello @DigitalFlow,

Are you planning in the near future to support RTL languages such as Arabic and or Hebrew ? At the moment the main issue is that the buttons on the split screen are not located in the right place:

Also is there any language pack we can use to translate it 

![Annotation 2021-02-01 101445](https://user-images.githubusercontent.com/78345071/106431724-5af73100-6476-11eb-941b-a3f7681d3905.png)

**Comment by DigitalFlow** [comment]
Hi @alexy18,

support should generally be given, I'll have to look into this.
Seems like a styling issue on my side.

Localization for the controls of PowerKanban is not yet available, but this is something that needs to be done.
I need to check the best way for loading extensions, maybe it would be valuable to have them in the official repository as well however.

I'll look into it.

Kind Regards,
Florian

**Comment by alexy18** [comment]
Thank you ! To tell the truth the language problem is not very significant
Like the position of the buttons it really looks like styling issue.

Most of the fields / buttons in the source language of the CRM so it is not really a 'serious problem' like the buttons.

**Comment by DigitalFlow** [comment]
Hi @alexy18,

Release [v0.9.28](https://github.com/XRM-OSS/D365-PowerKanban/releases/tag/v0.9.28) is out, featuring the fixes for the side panel buttons in RTL languages.
Please give it a try.

I hope you're in a safe place, recent news from Israel/Gaza have been quite shocking...

Kind regards,
Florian

**Comment by alexy18** [comment]
Hi @DigitalFlow , sorry for the late response.

Thanks so much for the update and the concern, these were not easy days we went through.

I saw the new support for RTL and it's amazing!
Your plugin is outstanding !!!

Do you want more feedback on improving RTL support?

**Comment by DigitalFlow** [comment]
Hi @alexy18,

thanks for your feedback, it is much appreciated :)

If there is anything malformatted that makes using this tool more difficult, please report it.

Kind regards,
Florian
