### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by alexy18** [XRM-OSS/D365-PowerKanban#49]
Hello,

We have tried the power on the account entity with custom field and we having the following error:

`{
    "primaryEntity": {
        "logicalName": "account",
        "swimLaneSource": "new_test"
    }
}` 

https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:5094 at https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:1619 at Object.next (https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:1724) at https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:636 at new Promise (<anonymous>) at o (https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:381) at T (https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:4916) at https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:6530 at https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:1619 at Object.next (https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:1724) at a (https://URL.crm4.dynamics.com/%7b637477626990000143%7d/webresources/cc_oss.PowerKanban/bundle.js:1376:438)

**Comment by DigitalFlow** [comment]
Hi @alexy18,

The json that you provided is valid, but is it your complete config?
Can you post your complete config and maybe a screenshot?

Kind Regards,
Florian

**Comment by alexy18** [comment]
Hello @DigitalFlow,

Below provided screenshot of PowerKanban Config record 

![PowerKanban Config](https://user-images.githubusercontent.com/78345071/106437906-6fd7c280-647e-11eb-8610-a65ed6fa4337.png)

**Comment by DigitalFlow** [comment]
I never saw right to left json, I'm not sure how that is handled, can you copy paste your json in here?
Does it

**Comment by alexy18** [comment]
Hi
The Json is not really right to left it's just because of the screen 
 
![image](https://user-images.githubusercontent.com/78345071/106441130-589ad400-6482-11eb-8b0d-8a9524d1dfb8.png)

**Comment by DigitalFlow** [comment]
But in there it is not right to left?
Can you copy the one from incident to the one in account and just change the values?

**Comment by alexy18** [comment]
![image](https://user-images.githubusercontent.com/78345071/106441567-dfe84780-6482-11eb-8366-505264b0eba2.png)


![image](https://user-images.githubusercontent.com/78345071/106441594-eaa2dc80-6482-11eb-99cc-8c905e2aa3af.png)

**Comment by DigitalFlow** [comment]
Ah sorry, can you try one thing?
The configs are cached for the duration of your browser session to improve the performance.
The config that you posted looks valid. Can you therefore close your browser completely and open PowerKanban again, to check whether the error disappears?

**Comment by alexy18** [comment]
you were right. I sign out from the browser I logged in again and it worked out

**Comment by DigitalFlow** [comment]
Great! :)

I will create a follow up issue to take care that configs are only cached after being parsed successfully however.

Kind Regards,
Florian
