### ISSUE TITLE
"Did not find any card forms for lead, please create one" Error Message

### ISSUE THREAD

**Issue by simonjeddy** [XRM-OSS/D365-PowerKanban#54]
Hi Florian!

Thanks for all the work on the Power Kanban PCF control. All went well, until I finished setting it up and was prompted with a message saying I did not have any Lead cards set up.
Under forms in Lead, I set up a new lead card, which we did not have before, and the Kanban view still did not work.

How are you able to get custom cards to work with the Power Kanban view on Leads?

I can send some more photos or something if need be.
![CRMerror](https://user-images.githubusercontent.com/78522985/106845494-a70dc580-6670-11eb-9a9d-377633b4e8c7.PNG)

Thanks for any insight!

**Comment by DigitalFlow** [comment]
Hi @simonjeddy,

thanks for the kind words :)

Currently metadata such as card forms and so on are cached by default for the lifetime of the browser session.
Cache is cleared on closing of your browser.

I think I will soon turn off metadata caching by default, as it is causing too many inconveniences in development.
For the time being, can you try closing your browser completely? That should clear your cache and afterwards the card forms should be shown.

Kind Regards,
Florian

**Comment by simonjeddy** [comment]
Florian,

That worked perfectly! I have it running now.

Although, we have mostly created different views of the lead or opportunity pages through "My Views" not by creating new System Views. I see that the Power Kanban layout only utilizes System Views. Is there a way to use My Views in the Power Kanban?

Thanks!

**Comment by simonjeddy** [comment]
The main reason for this is that we like to go through leads of different owners and sometimes update them together. I am having trouble creating a new system views for specific owners. Plus creating system views is a lot more of a PITA for the general user not familiar with the deeper workings of Dynamics & Power Apps.

**Comment by DigitalFlow** [comment]
Hi @simonjeddy,

user views can not yet be used. I'll take a look on fetching them, should be no big issue to implement :)

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
HI @simonjeddy,

please get the new release v0.9.22 and try.
For the primary entity we now use the Dynamics 365 default view selector. This enables you to choose user views as well as pinning views.

Feedback would be appreciated :)

Kind Regards,
Florian

**Comment by jdiekman** [comment]
Hi Florian, 

Great PCF. Have the same issue here. Followed clearing cache, closing browser, updated to new version. this occurs on the Opportunity table. Oddly it works on the incident table.

**Comment by DigitalFlow** [comment]
Hi @jdiekman,

so you created a card form for opportunity and it does not find any? Did you publish the entity?
Caching is not activated by default anymore, did you try in v0.9.24?

Kind regards,
Florian

**Comment by jdiekman** [comment]
Hi Florian, 

Got it working, I thought I was on the latest version, but wasn't - working now! great control and appreciate the prompt reply! 

Great work. 

James

**Comment by DigitalFlow** [comment]
Hi James,

you`re welcome, glad that you like it :)
I'll close this issue as the original question and enhancement were also already implemented.

Kind regards,
Florian
