### ISSUE TITLE
Split screen function throwing weird error

### ISSUE THREAD

**Issue by Mcai282** [XRM-OSS/D365-PowerKanban#61]
Hi,

When I'm using the split screen function it's throwing out this strange error (see below)

![image](https://user-images.githubusercontent.com/54522237/113648984-f1430f80-96d0-11eb-89f2-8894501ffa40.png)

I'm not too sure what could be causing this. Modal works fine though.

It also seems to be a strange transient error. After a while it seems to work fine again..

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

any chance that the entity where this error is thrown was imported rather recently inside your organization?
I experienced this quite often in CRM without even using PowerKanban. New entities seem to show this issues directly after being imported, after refreshing this is gone.

Inside PowerKanban there is nothing special happening when using splitscreen, it's just an IFrame of Dynamics with an URL option for hiding navigation elements.
Does this issue reoccur after it seems to work fine?

Kind Regards,
Florian

**Comment by Mcai282** [comment]
> Hi @Mcai282,
> 
> any chance that the entity where this error is thrown was imported rather recently inside your organization?
> I experienced this quite often in CRM without even using PowerKanban. New entities seem to show this issues directly after being imported, after refreshing this is gone.
> 
> Inside PowerKanban there is nothing special happening when using splitscreen, it's just an IFrame of Dynamics with an URL option for hiding navigation elements.
> Does this issue reoccur after it seems to work fine?
> 
> Kind Regards,
> Florian

Hey bud,

Thanks for the quick reply. Really love this PCF. The entity in question is actually opportunities. 

The issue does seem to reoccur quite regularly and randomly. My security role is a system admin role so it should be a access issue. 

The only other thing I can think of is that I have another PCF component on the opportunity form itself, which should be a issue if it's just a iFrame. Again it works fine in modal and when I open in a new window.

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

any chance you're using the Dynamics default model driven app and not a custom one?
I could imagine that it might be app related.

Kind Regards,
Florian

**Comment by Mcai282** [comment]
> Hi @Mcai282,
> 
> any chance you're using the Dynamics default model driven app and not a custom one?
> I could imagine that it might be app related.
> 
> Kind Regards,
> Florian

Thanks Florian,

I've actually created a custom model driven app and using this PCF. So it's not the default sales hub or customer service hub etc. 

The error message doesn't tell me much to be honest. Something with a Type of CustomerTest. Tried googling it and all I found was this error was thrown when trying to access Cloud Flows via the old solution interface..

![image](https://user-images.githubusercontent.com/54522237/113792270-dc29b780-9788-11eb-8a4a-5ad8b7fe5ebd.png)

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

`Record is unavailable` is also shown when the appId of the UCI model driven app is incorrect.

I need to try to trigger this issue as well on my side.
In the mean time, could you please copy the URL of the CRM page next time the PowerKanban shows this error? This would help me to check out which parameters it is parsing. The query string suffices, so everything after the ?.

I have a rough idea what might be happening, but need to verify.

Kind regards,
Florian

**Comment by Mcai282** [comment]
> Hi @Mcai282,
> 
> `Record is unavailable` is also shown when the appId of the UCI model driven app is incorrect.
> 
> I need to try to trigger this issue as well on my side.
> In the mean time, could you please copy the URL of the CRM page next time the PowerKanban shows this error? This would help me to check out which parameters it is parsing. The query string suffices, so everything after the ?.
> 
> I have a rough idea what might be happening, but need to verify.
> 
> Kind regards,
> Florian

Thanks Florian,

The query string is:
appid=b360fb86-bf86-eb11-a812-002248153690&pagetype=entitylist&etn=opportunity&viewid=8969c581-5797-eb11-b1ac-002248153eb6&viewType=1039

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

thanks a lot for your followup, this helps me a lot.
The IFrame is still using the old URL parameter "app" instead of the new "appid" one. I can fix that, expect a new version very soon :)

Kind regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

should be fixed in v0.9.25: https://github.com/XRM-OSS/D365-PowerKanban/releases/tag/v0.9.25
Can you give it a try?

Kind Regards,
Florian

**Comment by Mcai282** [comment]
Thanks Florian,

You rock!

**Comment by DigitalFlow** [comment]
Hi @Mcai282,

thanks a lot, I'm glad you like it.
In the mean time I noticed there was a race condition in the previous release, please update to v0.9.27: https://github.com/XRM-OSS/D365-PowerKanban/releases/tag/v0.9.27.

I'll close this issue :)

Kind Regards,
Florian
