### ISSUE TITLE
View Dropdown no longer available after upgrading to 0.9.27

### ISSUE THREAD

**Issue by tylerboswell** [XRM-OSS/D365-PowerKanban#68]
After upgrading from 0.9.21 I no longer see the view selector on the Kanban to choose from my visible views. This will completely break the way a client uses the features as a manager uses that dropdown to see the Leads for each user she manages (so another request for additional filters, see #33). I have tried recreating the view, recreating the config, and modifying the JSON but unfortunately nothing is working.

**Comment by DigitalFlow** [comment]
Hi @tylerboswell,

the dropdown has moved from within D365-PowerKanban back to the D365 default view selector, which is always above the Kanban.
Can you give it a try? This simplifies customization, as the default selector will respect the model driven app view filters, show personal views and allow to pin views.

Kind regards,
Florian

**Comment by tylerboswell** [comment]
I did notice that, but this just means that the visible views function is useless, correct?

**Comment by DigitalFlow** [comment]
Yes, that's true, at least for the primary entity.

You can still filter the views using the Model Driven App Designer, so it's only a replacement instead of a feature loss.

**Comment by tylerboswell** [comment]
It does, though ideally we would be able to add additional filters (like owner) rather than create a view for each individual if a manager wants to change which user they are looking at.

**Comment by DigitalFlow** [comment]
Adding additional filters is an open to do defined in #33.

Are you using a simple kanban at the moment, or already an advanced one with two entities?
If it's a simple kanban, you could define an extended one for managers, where the primary entity is the systemuser entity, set to a view which filters on the manager's team.

The advanced view could then list all records that the manager is interested in, grouped by the corresponding owning user.
That would be quite nice for the managers, right?

Imagine it like this, but with the outer containers being the users and the inner ones being the actual data:
![image](https://user-images.githubusercontent.com/4287938/118766789-35533380-b87d-11eb-98ac-8efe5cacd4e1.png)

**Comment by DigitalFlow** [comment]
Any addition to that, each manager could also create personal views for himself, where he filters on his team members.

If your team members have their manager set in their user profile, you could however even create a generic Manager view which shows all of his subordinates.

**Comment by tylerboswell** [comment]
That is a good thought! I'll see if the client has any interest in setting it up this way.
