### ISSUE TITLE
bug - Subscription/Notification functionality

### ISSUE THREAD

**Issue by acehaddock** [XRM-OSS/D365-PowerKanban#69]
We are using D365 Power Kanban, and recently we upgraded to the latest solution and trying to use the Subscription/Notification functionality.

We observed an issue with Subscription icon within the Kanban board. After we subscribe to a record, the icon still shows up as if it was NOT subscribed.
Please see the screenshot below:

![image](https://user-images.githubusercontent.com/24735301/119273524-f56bb380-bbd0-11eb-8793-19674bf6df37.png)

user subscribed to all these 3 records but the icon still shows up as if these records were not subscribed.

Is there a config we can use by which only Subscribe button will be displayed when record is NOT subscribed, and vice-versa ?

![image](https://user-images.githubusercontent.com/24735301/119273583-2ba93300-bbd1-11eb-83f3-755371c25813.png)

**Comment by DigitalFlow** [comment]
Hi @acehaddock,

are you sure that you are on v0.9.28?

I just checked at my side. When you are not subscribed, the icon shows like this:
![image](https://user-images.githubusercontent.com/4287938/119809011-f78d8500-bee4-11eb-8c2d-048dc27dc0ca.png)

After clicking the arrow down icon beside it and clicking on subscribe, it looks like this:
![image](https://user-images.githubusercontent.com/4287938/119808924-e04e9780-bee4-11eb-93f2-91a4579542e6.png)

This happens directly after clicking subscribe, no refresh or anything like that necessary.
Can you verify?

Kind regards,
Florian

**Comment by acehaddock** [comment]
Yes I will.

And it will be after the holidays FYI disconnecting a bit from tech 

Sent from my iPhone
Cole Haddock

**Comment by DigitalFlow** [comment]
Hi @acehaddock,

Any news on this? Otherwise I'd close this issue. I don't see any issues in my orgs.

Kind regards,
Florian

**Comment by DigitalFlow** [comment]
Closed due to inactivity. Please reopen in case of updates.

**Comment by acehaddock** [comment]
Sorry been Mia a bit I will check in the morning and let you know :-( 

Sent from my iPhone
Cole Haddock
