### ISSUE TITLE
Can't download latest managed solution

### ISSUE THREAD

**Issue by jimiryquai** [XRM-OSS/D365-PowerKanban#71]
I keep getting a 503 error when I try to download the managed solution here https://github.com/XRM-OSS/D365-PowerKanban/releases/tag/v0.9.28

**Comment by DigitalFlow** [comment]
Hi @jimiryquai,

seems to work for me without issues.
Can you try it on a different computer or your mobile phone?

Might be that a corporate proxy or something similar is blocking the download for you.
Some companies block downloads from GitHub.

Kind regards,
Florian

**Comment by jimiryquai** [comment]
Thanks Florian - all is well now. I think I must have been affected by those well publicised outages?
