### ISSUE TITLE
Default Drop down to advanced

### ISSUE THREAD

**Issue by Elkerton13** [XRM-OSS/D365-PowerKanban#72]
Hello, Is it possible to default the dropdown overflow to advanced. The users need to search primarily using the secondary entity. So it will look like the image attached.
<img width="1589" alt="Screenshot 2021-06-30 at 12 38 02" src="https://user-images.githubusercontent.com/86721358/123954245-14175400-d9a0-11eb-9b37-cd9ff4e8eb9e.png">

The Value I have at the moment is below:

{
    "primaryEntity": {
        "logicalName": "pre_tasktype",
        "swimLaneSource": "pre_tasktypedd"
    },
    "secondaryEntity": {
        "logicalName": "task",
        "parentLookup": "pre_tasktype",
        "swimLaneSource": "statuscode"
    }
}

**Comment by DigitalFlow** [comment]
Hi @Elkerton13,

yes this is possible, your configuration would look like this then:

```JSON
{
    "primaryEntity": {
        "logicalName": "pre_tasktype",
        "swimLaneSource": "pre_tasktypedd"
    },
    "secondaryEntity": {
        "logicalName": "task",
        "parentLookup": "pre_tasktype",
        "swimLaneSource": "statuscode"
    },
    "defaultDisplayState": "advanced"
}
```

Please give me some feedback whether this solved your question.

Kind regards,
Florian

**Comment by Elkerton13** [comment]
Fantastic, this works  perfectly - Thank you

**Comment by DigitalFlow** [comment]
Alright, glad that it helped you 👍

**Comment by Elkerton13** [comment]
Hello DigitalFlow, One more for you... Is it possible to turn the primary entity off and only display the secondary entity. Ideally I would like to be able to filter on the primary entity but only see the secondary cards.

**Comment by DigitalFlow** [comment]
Hi @Elkerton13,

this is not directly possible.
You can create another Kanban where you set your current secondary entity (task) as primary entity. You can then add the lookup to pre_tasktype to the card form, so that you can search for the name of your "pre_tasktype".

If you need to search for more than just the name, you can only make the card form of pre_tasktype as small as possible.

Kind regards,
Florian
