### ISSUE TITLE
Error with Virtual Entity

### ISSUE THREAD

**Issue by coderpsy** [XRM-OSS/D365-PowerKanban#73]
When I try to use kanban board with virtual entities I receive the error below. Virtual entity works fine if i deactivate power kanban.
Did anyone used virtual entity with power kanban before?

![image](https://user-images.githubusercontent.com/6233400/125408323-78381000-e3c3-11eb-9bd2-cc27cfcdf088.png)

**Comment by DigitalFlow** [comment]
Hi @coderpsy,

we did not ever try that out, but to me it seems that it should work. Metadata is available for virtual entities.
Can you post your PowerKanban configuration and a screenshot of the entity field which you tried to configure as swim lane?
A screenshot of the entity itself with its logical name would be helpful as well.

The casing of the logical names should be exactly the same as in the logical names inside the metadata for both the entity and the swim lane field.

Kind regards,
Florian

**Comment by coderpsy** [comment]
Hi,

Thanks for the quick response.

I noticed field name is wrong and changed it. 
The error disappeared but when I try to open the board it is stuck at fetching data window.
with f12 i get the following error 

> SyntaxError: Unexpected number in JSON at position 1
>     at JSON.parse (<anonymous>)
>     at p (https://uespoc.crm4.dynamics.com/%7b637617758590000131%7d/webresources/cc_oss.PowerKanban/bundle.js:294:1604)
>     at XMLHttpRequest.l.onload (https://uespoc.crm4.dynamics.com/%7b637617758590000131%7d/webresources/cc_oss.PowerKanban/bundle.js:294:4237)


![image](https://user-images.githubusercontent.com/6233400/125451964-a65d8871-4391-4851-aeff-3ff27b387e78.png)
![image](https://user-images.githubusercontent.com/6233400/125452015-648cbb63-e2d6-482d-8fff-b01c71ada40c.png)
![image](https://user-images.githubusercontent.com/6233400/125452086-7b5de5e2-79b1-4960-b8b5-c89242690054.png)

**Comment by DigitalFlow** [comment]
Hi @coderpsy,

can you press F12, go to the network tab and check for red entries? It would be interesting to find out what the failed request looked like and what the error message was.

You could also run `Xrm.WebApi.retrieveMultipleRecords("ad_kanban").then(console.log).catch(console.error)` and check whether this succeeds.

Kind regards,
Florian

**Comment by coderpsy** [comment]
Hi,
This is the error details.
As the error says I don't have "statuscode". I have "ad_statuscode" on ad_kanban entity.
and as you can see from previous comment on the config file I'm using ad_statuscode for swimlanesource.


--batchresponse_7281f6e9-0c1b-4c2a-b7d7-e34d4376d509
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 400 Bad Request
REQ_ID: 2d871ca5-7f3a-4070-b39b-4663b022a677
Content-Type: application/json; odata.metadata=minimal
OData-Version: 4.0

{"error":{"code":"0x80041103","message":"'ad_kanban' entity doesn't contain attribute with Name = 'statuscode' and NameMapping = 'Logical'. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=85222231, MinActiveRowVersion=85222231, MetadataInstanceId=31407863, LastUpdated=2021-07-14 07:00:35.397"}}
--batchresponse_7281f6e9-0c1b-4c2a-b7d7-e34d4376d509--

**Comment by DigitalFlow** [comment]
Hi @coderpsy,

thanks for the network log.

I did a quick check and did not find any hard coded 'statuscode' appearances inside my code.
Might be related to your view.

Can you please also include the request? Above shows only the response.
With the request I could check what was really tried to fetch.

Kind regards,
Florian

**Comment by coderpsy** [comment]
Payload was too long so i added complete request as file.
in this part both "statuscode" and "ad_statuscode" fields are getting retrieved. Can you tell me where this fields are received from so i can check that part from my customizations.

GET https://uespoc.crm4.dynamics.com/api/data/v8.0/ad_kanbans?fetchXml=%3Cfetch%20no-lock%3D%22true%22%3E%3Centity%20name%3D%22ad_kanban%22%3E%3Cattribute%20name%3D%22ad_kanbanid%22/%3E%3Cattribute%20name%3D%22statuscode%22/%3E%3Cattribute%20name%3D%22ad_kanbanname%22/%3E%3Cattribute%20name%3D%22createdon%22/%3E%3Cattribute%20name%3D%22ad_statuscode%22/%3E%3Cfilter%3E%3Ccondition%20attribute%3D%22ad_kanbanid%22%20operator%3D%22in%22%3E%3Cvalue%3E71b22d87-0cc9-eb11-bacc-000d3a26ee2f%3C/value%3E%3Cvalue%3Efb0239b8-22c9-eb11-bacc-000d3a26ee2f%3C/value%3E%3Cvalue%3E8c9d915d-25c9-eb11-bacc-000d3a26ee2f%3C/value%3E%3Cvalue%3E818c9ec3-d19b-e911-a83f-000d3a3852a3%3C/value%3E%3Cvalue%3E532330dc-d19b-e911-a83f-000d3a3852a3%3C/value%3E%3Cvalue%3E465d58f4-d19b-e911-a83f-000d3a3852a3%3C/value%3E%3Cvalue%3Ec657a606-d29b-e911-a83f-000d3a3852a3%3C/value%3E%3Cvalue%3E45ef0d1f-d29b-e911-a83f-000d3a3852a3%3C/.....

[request headers.txt](https://github.com/XRM-OSS/D365-PowerKanban/files/6814952/request.headers.txt)
[request payload.txt](https://github.com/XRM-OSS/D365-PowerKanban/files/6814953/request.payload.txt)

**Comment by DigitalFlow** [comment]
Hi @coderpsy,

PowerKanban builds a dynamic fetch based on the view filter criteria and only including the columns that are included in the card form that is used.
Can you check whether your card form contains a statuscode field? I think there is a field for card coloring in card forms that defaults to statuscode, you might want to check on that.

You can also send me the formXml if you want.

Kind regards,
Florian

**Comment by coderpsy** [comment]
As you said xml file of the form contains statuscode. This field is not visible on form customization so i totally missed it :)

I will try to find a solution.
Thank you very much for your help

"<control id="statuscode" classid="{5D68B988-0661-4db2-BC3E-17598AD3BE6C}" datafieldname="statuscode" disabled="false" />"

[xml.txt](https://github.com/XRM-OSS/D365-PowerKanban/files/6815573/xml.txt)

**Comment by DigitalFlow** [comment]
Hi @coderpsy,

glad to have that confirmed and thanks for sending in the XML :)
Would be great to have feedback from you whether everything worked after you removed that control from the form.

Kind regards,
Florian

**Comment by coderpsy** [comment]
Hi @DigitalFlow 

I removed statuscode control and kanban board works now :)
Thanks for your help 

Best Regards

**Comment by DigitalFlow** [comment]
Hi @coderpsy,

that's great to hear, awesome :)
How is the performance? Could be a little bit slower to load virtual entity data, right?

Kind regards,
Florian

**Comment by coderpsy** [comment]
@DigitalFlow 
Yeah it is a bit slower than standart entities. I'm testing with close to 900 records and it is 2-3 seconds slower.

**Comment by DigitalFlow** [comment]
@coderpsy
Sounds still pretty reasonable, thanks for the feedback :)
