### ISSUE TITLE
Example of Custom Button

### ISSUE THREAD

**Issue by surfmaverick** [XRM-OSS/D365-PowerKanban#76]
Is there an example of a custom button that results in the update of a field on the incident/record I can follow?

Basically what I would like to do is place a button on the card that when clicked brings up a dialogue to update a field on the record.

**Comment by DigitalFlow** [comment]
Hi @surfmaverick,

there is an example, however I think it's a little incomplete right now.
You can take a look here: https://github.com/XRM-OSS/D365-PowerKanban/wiki/Custom-Buttons

Basically you would extend your Powerkanban Config to look something like this:
```JSON
{
    "primaryEntity": {
        "logicalName": "incident",
        "swimLaneSource": "statuscode",
        "customButtons": [
            {
                "id": "someButtonId",
                icon: { type: "fluent"; value: ""; };
                "label": "Label Of your Button",
                "callBack": "boardViewExtender.onPrimaryClick"
            }
        ]
    }
}
```

your script would be something like


```JS
window.boardViewExtender = {};

window.boardViewExtender.onPrimaryClick = function (context) {
    return context.showForm({
        title: "Title of your form",
        fields: {
            "subject": {
                label: "Subject",
                type: "text",
                required: true,
                subtext: "Please enter a summary how the case was solved"
            },
            "timespent": {
                label: "Time spent",
                type: "number",
                required: true,
                subtext: "How long did it take you to solve this case (in minutes)?"                
            },
            "description": {
                label: "Description",
                type: "text",
                as: "textarea",
                rows: 5,
                required: true,
                subtext: "Please describe how the case was solved"
            }/*,
            "contact": {
                label: "Contact",
                type: "lookup",
                required: true,
                subtext: "This is only for showcasing that lookups are supported as well",
                fetchXml: '<fetch><entity name="contact"><attribute name="fullname" /><attribute name="emailaddress1" /><attribute name="gendercode" /> <attribute name="parentcustomerid" /><order attribute="fullname" /></entity></fetch>',
                secondaryFields: ["emailaddress1", "gendercode", "parentcustomerid"],
                displayField: "fullname"
            }*/
        }
    })
    .then(formResult => {
        if (!formResult.cancelled) {
            context.setWorkIndicator(true);

            const closeRequest = context.WebApiClient.Requests.CloseIncidentRequest.with({
                payload: {
                    IncidentResolution: {
                        "incidentid@odata.bind": `/incidents(${context.data.incidentid})`,
                        subject: formResult.values.subject,
                        timespent: formResult.values.timespent,
                        description: formResult.values.description
                    },
                    Status: context.target.Value
                }
            });

            return context.WebApiClient.Execute(closeRequest)
            .then(() => {
                context.setWorkIndicator(false);
                return context.refresh()
            })
            .then(() => {
                return null;
            })
            .catch(e => Xrm.Utility.alertDialog(e.message || e, () => {}));
        }

        return null;
    });
};
```

Please give me some feedback whether you managed to implement it with my example.

Kind regards,
Florian

**Comment by surfmaverick** [comment]
Okay - thanks - I’ll take a stab at it and get back to you.

**Comment by surfmaverick** [comment]
Hi Florian,

How do we update a field on the record from the context.data?

Chris

**Comment by surfmaverick** [comment]
Thanks. Here's the script we ended up using, and it worked well.

---


window.boardViewExtender = {};

window.boardViewExtender.styleCallback = function(context) {
    // Initiate style object with default properties that you want to apply always. Leave empty for not modifying anything by default.
    const style = { borderTop: "3px solid green" };
    
    // oss_duedate is a date field which is included in the card form. All card form data can be found in context.data
    if (context.data.new_duedate) {
        const hourDiff = Math.ceil((Date.parse(context.data.new_duedate) - Date.parse(new Date().toISOString())) / (1000*60*60));

        if (hourDiff < 168) {
            style.borderTop = "3px solid red";
        } 
    }
    
    if (context.data.scheduledend) {
        const hourDiff = Math.ceil((Date.parse(context.data.scheduledend) - Date.parse(new Date().toISOString())) / (1000*60*60));

        if (hourDiff < 168) {
            style.borderTop = "3px solid red";
        } 
    }
    
    return style;
};


window.boardViewExtender.onStateTransition = function(context) {
    /*if (![5, 1000].includes(context.target.Value)) {
        return;
    }*/
    
    return context.showForm({
        title: "Update Current Situation",
        fields: {
            "situation": {
                label: "Situation",
                type: "text",
                as: "textarea",
                rows: 5,
                required: true,
                subtext: "Please enter the current situation update."
            }
        }
    })
    .then(formResult => {
        if (!formResult.cancelled) {
            context.setWorkIndicator(true);

	    context.WebApiClient.Update({
		entityName: "incident",
		entityId: context.data.incidentid,
		entity: {
		   new_currentstatus: formResult.values.situation
		}
	    }).then(() => {
		context.refresh();
	    });
        }

        return { preventDefault: true };
    });
};

window.boardViewExtender.onPrimaryClick = function (context) {
    alert("Primary button clicked");
};

window.boardViewExtender.onSecondaryClick = function (context) {
    alert("Secondary button clicked");
};

**Comment by DigitalFlow** [comment]
Hi @surfmaverick,

thanks for posting the code here and great job for getting it to work! 👍 
Everything looks good as far as I can tell, glad that you found the context.WebApiClient as well for doing the updates.

Do you feel confident closing this issue?

Kind regards,
Florian

**Comment by surfmaverick** [comment]
Yes! All set!  Works great
