### ISSUE TITLE
Question re subscription and notification

### ISSUE THREAD

**Issue by surfmaverick** [XRM-OSS/D365-PowerKanban#77]
I couldn't follow this instruction in the wiki: "You need to configure the Xrm.Oss.PowerKanban.CreateNotification plugin with new plugin steps registered to the entity events that interest you. You should register your steps on post stage, if possible in asynchronous mode."

Could you please provide more detail or a more specific example?

**Comment by DigitalFlow** [comment]
Hi @surfmaverick,

did you see the examples section? https://github.com/XRM-OSS/D365-PowerKanban/wiki/Subscriptions-and-Notifications#examples

Basically there is a Plugin Assembly `Xrm.Oss.PowerKanban.CreateNotification` deployed with the PowerKanban solution. You can just open the Plugin Registration Tool, head to the above assembly and add a new plugin execution step.
For example if you want to notify on a Service Case when a new task regarding the case was created, you would create a new plugin execution step on Create of task entity and pass the configuration from here inside the Unsecure Configuration text field:
https://github.com/XRM-OSS/D365-PowerKanban/wiki/Subscriptions-and-Notifications#events-on-sub-entity-of-subscribed-record

Any questions left?

Kind regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @surfmaverick,

I hope my answer helped you setting up the plugin.
If anything is left unclear, feel free to reopen.

Kind regards,
Florian
