### ISSUE TITLE
visibleLanes doesn't work for me

### ISSUE THREAD

**Issue by molyom** [XRM-OSS/D365-PowerKanban#88]
Hi Florian, 
Thanks a lot for your share this with the community. 

I have created a JSON config like below:
**{
    "primaryEntity": {
        "logicalName": "opportunity",
        "swimLaneSource": "vision",
 "transitionCallback": "ValidationforKanban",
       "defaultOpenHandler":"modal",
 "visibleLanes": [
                        [10,30,50,70]
                    ]
    },
    "secondaryEntity": {
        "logicalName": "task",
        "parentLookup": "regardingobjectid",
        "swimLaneSource": "statuscode"
    },
    "customScriptUrl": "/WebResources/pes_/js/my_form.js"
}**

But this configuration doesn't show me the visible lanes as expected. 

If I remove below form config: 
 **"visibleLanes": [
                        [10,30,50,70]
                    ]
    }**

It works fine. 

I pass an array to visibleLanes as my OptionSet Values. (My optionSet Values are:  10,20,30,50,70,90,100  and just want to have 10, 20, 30, 50, 70 in PowerKanban. 

Can you help me to config it?
Thanks

**Comment by BugsOli** [comment]
Hello, the wiki example is incorrect, you are passing an array of arrays, which will not work.
The correct form is:
"visibleLanes": [10,30,50,70]

**Comment by molyom** [comment]
Thanks, RESOLVED.

**Comment by DigitalFlow** [comment]
Hi @molyom,

thanks for raising this issue and sorry for responding this late.
Thanks for providing assistance @BugsOli, you're totally right, this is how the visibleLanes have to be defined.

The wiki example is a JSON schema, where examples are an array themselves, as you could provide multiple examples.
So the wiki is technically correct, but I have to admit that JSON schema is a little misleading in that case.

Kind regards,
Florian
